config/routes.rb
Rollcall::Application.routes.draw do
  get '/attendances/new', controller: 'attendances', action: 'new', :as => 'new_attendance'
  post '/attendances', controller: 'attendances', action: 'create'

  get '/attendances', controller: 'attendances', action: 'index'
  get '/attendances/:id', controller: 'attendances', action: 'show', :as => 'attendance'

  get '/attendances/:id/edit', controller: 'attendances', action: 'edit', :as => 'edit_attendance'
  patch '/attendances/:id', controller: 'attendances', action: 'update'

  delete '/attendances/:id', controller: 'attendances', action: 'destroy'

  get '/students/new', controller: 'students', action: 'new', :as => 'new_student'
  post '/students', controller: 'students', action: 'create'

  get '/students', controller: 'students', action: 'index'
  get '/students/:id', controller: 'students', action: 'show', :as => 'student'

  get '/students/:id/edit', controller: 'students', action: 'edit', :as => 'edit_student'
  patch '/students/:id', controller: 'students', action: 'update'

  delete '/students/:id', controller: 'students', action: 'destroy'

  root "meetings#index"

  get '/meetings/new', controller: 'meetings', action: 'new', :as => 'new_meeting'
  post '/meetings', controller: 'meetings', action: 'create'

  get '/meetings', controller: 'meetings', action: 'index'
  get '/meetings/:id', controller: 'meetings', action: 'show', :as => 'meeting'

  get '/meetings/:id/edit', controller: 'meetings', action: 'edit', :as => 'edit_meeting'
  patch '/meetings/:id', controller: 'meetings', action: 'update'

  delete '/meetings/:id', controller: 'meetings', action: 'destroy'

  get '/courses/new', controller: 'courses', action: 'new', :as => 'new_course'
  post '/courses', controller: 'courses', action: 'create'

  get '/courses', controller: 'courses', action: 'index'
  get '/courses/:id', controller: 'courses', action: 'show', :as => 'course'

  get '/courses/:id/edit', controller: 'courses', action: 'edit', :as => 'edit_course'
  patch '/courses/:id', controller: 'courses', action: 'update'

  delete '/courses/:id', controller: 'courses', action: 'destroy'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def index
    @attendances = Attendance.all
  end

  def show
    @attendance = Attendance.find_by(:id => params[:id])

    @student = Student.find_by(:id => @attendance.student_id)

  end

  def new
    @students = Student.all
    @meetings = Meeting.all

  end

  def create
    @attendance = Attendance.new
    @attendance.meeting_id = params[:meeting_id]
    @attendance.student_id = params[:student_id]
    
    if @attendance.save
      redirect_to attendances_url
    else
      render 'new'
    end
  end

  def edit
    @attendance = Attendance.find_by(:id => params[:id])
  end

  def update
    @attendance = Attendance.find_by(:id => params[:id])
    @attendance.meeting_id = params[:meeting_id]
    @attendance.student_id = params[:student_id]
    
    if @attendance.save
      redirect_to attendances_url
    else
      render 'new'
    end
  end

  def destroy
    @attendance = Attendance.find_by(:id => params[:id])
    @attendance.destroy
    redirect_to attendances_url
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find_by(:id => params[:id])

    @meetings = Meeting.where(:course_id => @course.id)

  end

  def new
  end

  def create
    @course = Course.new
    @course.department = params[:department]
    @course.number = params[:number]
    @course.title = params[:title]
    
    if @course.save
      redirect_to courses_url
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find_by(:id => params[:id])
  end

  def update
    @course = Course.find_by(:id => params[:id])
    @course.department = params[:department]
    @course.number = params[:number]
    @course.title = params[:title]
    
    if @course.save
      redirect_to courses_url
    else
      render 'new'
    end
  end

  def destroy
    @course = Course.find_by(:id => params[:id])
    @course.destroy
    redirect_to courses_url
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    @meetings = Meeting.all

  end

  def show
    @meeting = Meeting.find_by(:id => params[:id])
    @course = Course.find_by(:id => @meeting.course_id)
    @attendance = Attendance.where(:meeting_id => @meeting.id)
   
  end

  def new
    @courses = Course.all
  end

  def create
    @meeting = Meeting.new
    @meeting.held_on = params[:held_on]
    @meeting.course_id = params[:course_id]
    

    if @meeting.save
      redirect_to meetings_url
    else
      render 'new'
    end
  end

  def edit
    @meeting = Meeting.find_by(:id => params[:id])
  end

  def update
    @meeting = Meeting.find_by(:id => params[:id])
    @meeting.held_on = params[:held_on]
    @meeting.course_id = params[:course_id]
    
    if @meeting.save
      redirect_to meetings_url
    else
      render 'new'
    end
  end

  def destroy
    @meeting = Meeting.find_by(:id => params[:id])
    @meeting.destroy
    redirect_to meetings_url
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(:id => params[:id])
  end

  def new
  end

  def create
    @student = Student.new
    @student.first_name = params[:first_name]
    @student.last_name = params[:last_name]
    
    if @student.save
      redirect_to students_url
    else
      render 'new'
    end
  end

  def edit
    @student = Student.find_by(:id => params[:id])
  end

  def update
    @student = Student.find_by(:id => params[:id])
    @student.first_name = params[:first_name]
    @student.last_name = params[:last_name]
    
    if @student.save
      redirect_to students_url
    else
      render 'new'
    end
  end

  def destroy
    @student = Student.find_by(:id => params[:id])
    @student.destroy
    redirect_to students_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/edit.html.erb
<div class="page-header">
  <h1>Editing Attendance #<%= @attendance.id %></h1>
</div>

<%= form_tag(attendance_url(@attendance), method: 'patch', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :meeting_id, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-2">
      <%= number_field_tag :meeting_id, @attendance.meeting_id, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :student_id, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-2">
      <%= number_field_tag :student_id, @attendance.student_id, class: 'form-control'%>
    </div>
  </div>

  
    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
          <%= submit_tag "Update Attendance", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/attendances/index.html.erb
<div class="page-header">
  <h1>Attendances</h1>
</div>

<p><%= link_to 'Add a New Attendance', new_attendance_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Meeting</th>
      <th>Student</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @attendances.each do |attendance| %>
    <tr>
      <% student = Student.find_by(:id => attendance.student_id) %>
      <% meeting = Meeting.find_by(:id => attendance.meeting_id) %>
      <% course = Course.find_by(:id => meeting.course_id) %>
        <td><%= meeting.held_on %> <%= course.department %> <%= course.number %> <%= course.title %></td>
        <td><%= student.first_name %> <%= student.last_name %></td>
        
<!--        <td><%= attendance.meeting_id %></td>
        <td><%= attendance.student_id %></td> -->
  
      <td><%= link_to '<i class="icon-zoom-in"></i>'.html_safe, attendance_url(attendance), class: 'btn btn-primary' %></td>
      <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_attendance_url(attendance), class: 'btn btn-warning' %></td>
      <td><%= link_to '<i class="icon-trash"></i>'.html_safe, attendance_url(attendance), method: 'delete', data: { confirm: "Do you really want to delete this attendance?" }, class: 'btn btn-danger' %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/attendances/new.html.erb
<div class="page-header">
  <h1>New Attendance</h1>
</div>

<%= form_tag(attendances_url, method: 'post', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :meeting_id, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-2">

          <select name="meeting_id">
      <% @meetings.each do |meeting| %>
      <% course = Course.find_by(:id => meeting.course_id) %>
        <option value="<%= meeting.id %>"><%= meeting.held_on %> <%= course.department %> <%= course.number %> <%= course.title %>
        </option> 
      <% end %>

        </select>
      <!--<%= number_field_tag :meeting_id, nil, class: 'form-control' %>-->


    </div>
  </div>

    <div class="form-group">
    <%= label_tag :student_id, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-2">

      <select name="student_id">


<% @students.each do |student| %>

  <option value="<%= student.id %>"><%= student.first_name %> <%= student.last_name %> </option> 
<% end %>

</select>


      <!--<%= number_field_tag :student_id, nil, class: 'form-control' %>-->




    </div>
  </div>

    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Attendance", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/attendances/show.html.erb
<div class="page-header">
  <h1>Attendance #<%= @attendance.id %></h1>
</div>

<p>
  <b>Meeting:</b>
  <%= @attendance.meeting_id %>
</p>

<p>
  <b>Student:</b>
  
  <%= @student.first_name %> <%= @student.last_name %>
</p>

app/views/courses/edit.html.erb
<div class="page-header">
  <h1>Editing Course #<%= @course.id %></h1>
</div>

<%= form_tag(course_url(@course), method: 'patch', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :department, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :department, @course.department, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :number, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :number, @course.number, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :title, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :title, @course.title, class: 'form-control'%>
    </div>
  </div>

  
    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
          <%= submit_tag "Update Course", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/courses/index.html.erb
<div class="page-header">
  <h1>Courses</h1>
</div>

<p><%= link_to 'Add a New Course', new_course_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Department</th>
      <th>Number</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
    <tr>
        <td><%= course.department %></td>
        <td><%= course.number %></td>
        <td><%= course.title %></td>
  
      <td><%= link_to '<i class="icon-zoom-in"></i>'.html_safe, course_url(course), class: 'btn btn-primary' %></td>
      <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_course_url(course), class: 'btn btn-warning' %></td>
      <td><%= link_to '<i class="icon-trash"></i>'.html_safe, course_url(course), method: 'delete', data: { confirm: "Do you really want to delete this course?" }, class: 'btn btn-danger' %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<div class="page-header">
  <h1>New Course</h1>
</div>

<%= form_tag(courses_url, method: 'post', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :department, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :department, nil, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
    <%= label_tag :number, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :number, nil, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
    <%= label_tag :title, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :title, nil, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Course", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/courses/show.html.erb
<div class="page-header">
  <h1>Course <%= @course.department %> <%= @course.number %> <%= @course.title %></h1>
</div>

<p>
  <b>Department:</b>
  <%= @course.department %>
</p>

<p>
  <b>Number:</b>
  <%= @course.number %>
</p>

<p>
  <b>Title:</b>
  <%= @course.title %>
</p>

<p>
  <b>Meetings:</b>

  <% @meetings.each do |meeting| %>
  	<p><%= meeting.held_on %></p>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Rollcall</title>

  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Rollcall</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <li><%= link_to "Home", "/" %></li>
          <li><%= link_to "Courses", "/courses" %></li>
          <li><%= link_to "Meetings", "/meetings" %></li>
          <li><%= link_to "Students", "/students" %></li>
          <li><%= link_to "Attendances", "/attendances" %></li>
          <li><a href="#about">About</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">

    <% if flash[:notice].present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/meetings/edit.html.erb
<div class="page-header">
  <h1>Editing Meeting #<%= @meeting.id %></h1>
</div>

<%= form_tag(meeting_url(@meeting), method: 'patch', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :held_on, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :held_on, @meeting.held_on, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :course_id, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-2">
      <%= number_field_tag :course_id, @meeting.course_id, class: 'form-control'%>
    </div>
  </div>

  
    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
          <%= submit_tag "Update Meeting", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/meetings/index.html.erb
<div class="page-header">
  <h1>Meetings</h1>
</div>

<p><%= link_to 'Add a New Meeting', new_meeting_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Held on</th>
      <th>Course</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @meetings.each do |meeting| %>
  <% course = Course.find_by(:id => meeting.course_id) %>
    <tr>
        <td><%= meeting.held_on %></td>
        <td><%= course.department %> <%= course.number %> <%= course.title %></td>
  
      <td><%= link_to '<i class="icon-zoom-in"></i>'.html_safe, meeting_url(meeting), class: 'btn btn-primary' %></td>
      <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_meeting_url(meeting), class: 'btn btn-warning' %></td>
      <td><%= link_to '<i class="icon-trash"></i>'.html_safe, meeting_url(meeting), method: 'delete', data: { confirm: "Do you really want to delete this meeting?" }, class: 'btn btn-danger' %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/new.html.erb
<div class="page-header">
  <h1>New Meeting</h1>
</div>

<%= form_tag(meetings_url, method: 'post', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :held_on, nil, class: 'col-md-2 control-label' %>

    <div class="col-md-6">
      <%= text_field_tag :held_on, nil, class: 'form-control' %>

    </div>
  </div>

    <div class="form-group">
    <%= label_tag :course_id, nil, class: 'col-md-2 control-label' %>

    <div class="col-md-2">

<select name="course_id">


<% @courses.each do |course| %>

  <option value="<%= course.id %>"><%= course.department %> <%= course.number %> <%= course.title %></option>
<% end %>

</select>

     <!-- <%= number_field_tag :course_id, nil, class: 'form-control' %> -->


    </div>
  </div>

    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Meeting", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/meetings/show.html.erb
<div class="page-header">
  <h1>Meeting #<%= @meeting.id %></h1>
</div>

<p>
  <b>Held on:</b>
  <%= @meeting.held_on %>
</p>

<p>
  <b>Course:</b>
  <%= @course.department %> <%= @course.number %> <%= @course.title %>
</p>

<p>
  <b>Students:</b>

  	<% @attendance.each do |attendance| %>
  	<% student = Student.find_by(:id => attendance.student_id) %>
  	<p><%= student.first_name %> <%= student.last_name %> </p>

<% end %>
</p>

app/views/students/edit.html.erb
<div class="page-header">
  <h1>Editing Student #<%= @student.id %></h1>
</div>

<%= form_tag(student_url(@student), method: 'patch', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :first_name, @student.first_name, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :last_name, @student.last_name, class: 'form-control'%>
    </div>
  </div>

  
    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
          <%= submit_tag "Update Student", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/students/index.html.erb
<div class="page-header">
  <h1>Students</h1>
</div>

<p><%= link_to 'Add a New Student', new_student_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
  
      <td><%= link_to '<i class="icon-zoom-in"></i>'.html_safe, student_url(student), class: 'btn btn-primary' %></td>
      <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_student_url(student), class: 'btn btn-warning' %></td>
      <td><%= link_to '<i class="icon-trash"></i>'.html_safe, student_url(student), method: 'delete', data: { confirm: "Do you really want to delete this student?" }, class: 'btn btn-danger' %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<div class="page-header">
  <h1>New Student</h1>
</div>

<%= form_tag(students_url, method: 'post', class: 'form-horizontal') do %>

  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :first_name, nil, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    
    <div class="col-md-6">
      <%= text_field_tag :last_name, nil, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Student", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/students/show.html.erb
<div class="page-header">
  <h1>Student #<%= @student.id %></h1>
</div>

<p>
  <b>First name:</b>
  <%= @student.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @student.last_name %>
</p>